# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/summary-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/summary-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/summary-service.proto\x12\x0fsummary_service\"!\n\x0eSummaryRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\"I\n\x0fSummaryResponse\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tion_items\x18\x03 \x03(\t2`\n\x0eSummaryService\x12N\n\tSummarize\x12\x1f.summary_service.SummaryRequest\x1a .summary_service.SummaryResponseBbZ`github.com/RoseWrightdev/Video-Conferencing/backend/go/gen/summary_service/proto;summary_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.summary_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z`github.com/RoseWrightdev/Video-Conferencing/backend/go/gen/summary_service/proto;summary_service'
  _globals['_SUMMARYREQUEST']._serialized_start=48
  _globals['_SUMMARYREQUEST']._serialized_end=81
  _globals['_SUMMARYRESPONSE']._serialized_start=83
  _globals['_SUMMARYRESPONSE']._serialized_end=156
  _globals['_SUMMARYSERVICE']._serialized_start=158
  _globals['_SUMMARYSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
