// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: proto/cc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";

export const protobufPackage = "cc";

export interface AudioChunk {
  /** Unique ID for the audio stream/user */
  sessionId: string;
  /** Raw PCM audio */
  audioData: Uint8Array;
  /** Optional: ISO code (e.g., "en", "es"). If empty, defaults to transcription. */
  targetLanguage: string;
}

export interface CaptionEvent {
  sessionId: string;
  text: string;
  isFinal: boolean;
  confidence: number;
}

function createBaseAudioChunk(): AudioChunk {
  return { sessionId: "", audioData: new Uint8Array(0), targetLanguage: "" };
}

export const AudioChunk: MessageFns<AudioChunk> = {
  encode(message: AudioChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.audioData.length !== 0) {
      writer.uint32(18).bytes(message.audioData);
    }
    if (message.targetLanguage !== "") {
      writer.uint32(26).string(message.targetLanguage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audioData = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetLanguage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<AudioChunk>, I>>(base?: I): AudioChunk {
    return AudioChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioChunk>, I>>(object: I): AudioChunk {
    const message = createBaseAudioChunk();
    message.sessionId = object.sessionId ?? "";
    message.audioData = object.audioData ?? new Uint8Array(0);
    message.targetLanguage = object.targetLanguage ?? "";
    return message;
  },
};

function createBaseCaptionEvent(): CaptionEvent {
  return { sessionId: "", text: "", isFinal: false, confidence: 0 };
}

export const CaptionEvent: MessageFns<CaptionEvent> = {
  encode(message: CaptionEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.isFinal !== false) {
      writer.uint32(24).bool(message.isFinal);
    }
    if (message.confidence !== 0) {
      writer.uint32(33).double(message.confidence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CaptionEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCaptionEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.confidence = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CaptionEvent>, I>>(base?: I): CaptionEvent {
    return CaptionEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CaptionEvent>, I>>(object: I): CaptionEvent {
    const message = createBaseCaptionEvent();
    message.sessionId = object.sessionId ?? "";
    message.text = object.text ?? "";
    message.isFinal = object.isFinal ?? false;
    message.confidence = object.confidence ?? 0;
    return message;
  },
};

export interface CaptioningService {
  /** Bidirectional streaming: SFU sends audio chunks, Service sends back captions. */
  StreamAudio(request: Observable<AudioChunk>): Observable<CaptionEvent>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
