// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: proto/sfu.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { CaptionEvent, TrackAddedEvent } from "./signaling";

export const protobufPackage = "sfu";

/** CreateSessionRequest is the payload to initialize a new session. */
export interface CreateSessionRequest {
  /** Unique identifier for the conference room */
  roomId: string;
  /** Unique identifier for the participant */
  userId: string;
}

/** CreateSessionResponse contains the initial signaling data from the SFU. */
export interface CreateSessionResponse {
  /** The SDP Offer generated by the SFU's PeerConnection */
  sdpOffer: string;
}

/** SignalMessage carries WebRTC signaling data from the Go Backend (proxying the Client) to the SFU. */
export interface SignalMessage {
  /** Unqiue identifier for the conference room */
  roomId: string;
  /** Unique identifier for the participant */
  userId: string;
  /** SDP Answer from the client (in response to SFU's Offer) */
  sdpAnswer?:
    | string
    | undefined;
  /** Trickle ICE candidate from the client */
  iceCandidate?:
    | string
    | undefined;
  /** SDP Offer from the client (for renegotiation) */
  sdpOffer?: string | undefined;
}

/** SignalResponse indicates whether the SFU successfully processed the signal. */
export interface SignalResponse {
  success: boolean;
}

/** DeleteSessionRequest asks the SFU to disconnect a user. */
export interface DeleteSessionRequest {
  /** Unique identifier for the conference room */
  roomId: string;
  /** Unique identifier for the participant (peer to remove) */
  userId: string;
}

/** DeleteSessionResponse indicates success of the teardown operation. */
export interface DeleteSessionResponse {
  success: boolean;
}

/** ListenRequest establishes the event stream for a specific session. */
export interface ListenRequest {
  roomId: string;
  userId: string;
}

/** SfuEvent represents an asynchronous event occurring within the SFU that the Backend/Client needs to know about. */
export interface SfuEvent {
  /**
   * DEPRECATED: Use track_event
   *
   * @deprecated
   */
  trackAddedUserId?:
    | string
    | undefined;
  /**
   * DEPRECATED: Use track_event
   *
   * @deprecated
   */
  trackAddedStreamId?:
    | string
    | undefined;
  /**
   * Notification that a new track has been added to the room.
   * The Backend should relay this to clients so they can subscribe.
   */
  trackEvent?:
    | TrackAddedEvent
    | undefined;
  /** Request to renegotiate the WebRTC connection. */
  renegotiateSdpOffer?:
    | string
    | undefined;
  /** SDP Answer generated by the SFU (in response to a client's Offer). */
  sdpAnswer?:
    | string
    | undefined;
  /**
   * Trickle ICE candidate generated by the SFU.
   * The Backend should forward this to the specific client.
   */
  iceCandidate?:
    | string
    | undefined;
  /** Caption event to be forwarded to clients. */
  caption?: CaptionEvent | undefined;
}

function createBaseCreateSessionRequest(): CreateSessionRequest {
  return { roomId: "", userId: "" };
}

export const CreateSessionRequest: MessageFns<CreateSessionRequest> = {
  encode(message: CreateSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CreateSessionRequest>, I>>(base?: I): CreateSessionRequest {
    return CreateSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionRequest>, I>>(object: I): CreateSessionRequest {
    const message = createBaseCreateSessionRequest();
    message.roomId = object.roomId ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseCreateSessionResponse(): CreateSessionResponse {
  return { sdpOffer: "" };
}

export const CreateSessionResponse: MessageFns<CreateSessionResponse> = {
  encode(message: CreateSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sdpOffer !== "") {
      writer.uint32(10).string(message.sdpOffer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sdpOffer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CreateSessionResponse>, I>>(base?: I): CreateSessionResponse {
    return CreateSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionResponse>, I>>(object: I): CreateSessionResponse {
    const message = createBaseCreateSessionResponse();
    message.sdpOffer = object.sdpOffer ?? "";
    return message;
  },
};

function createBaseSignalMessage(): SignalMessage {
  return { roomId: "", userId: "", sdpAnswer: undefined, iceCandidate: undefined, sdpOffer: undefined };
}

export const SignalMessage: MessageFns<SignalMessage> = {
  encode(message: SignalMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.sdpAnswer !== undefined) {
      writer.uint32(26).string(message.sdpAnswer);
    }
    if (message.iceCandidate !== undefined) {
      writer.uint32(34).string(message.iceCandidate);
    }
    if (message.sdpOffer !== undefined) {
      writer.uint32(42).string(message.sdpOffer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdpAnswer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.iceCandidate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sdpOffer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SignalMessage>, I>>(base?: I): SignalMessage {
    return SignalMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignalMessage>, I>>(object: I): SignalMessage {
    const message = createBaseSignalMessage();
    message.roomId = object.roomId ?? "";
    message.userId = object.userId ?? "";
    message.sdpAnswer = object.sdpAnswer ?? undefined;
    message.iceCandidate = object.iceCandidate ?? undefined;
    message.sdpOffer = object.sdpOffer ?? undefined;
    return message;
  },
};

function createBaseSignalResponse(): SignalResponse {
  return { success: false };
}

export const SignalResponse: MessageFns<SignalResponse> = {
  encode(message: SignalResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SignalResponse>, I>>(base?: I): SignalResponse {
    return SignalResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignalResponse>, I>>(object: I): SignalResponse {
    const message = createBaseSignalResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseDeleteSessionRequest(): DeleteSessionRequest {
  return { roomId: "", userId: "" };
}

export const DeleteSessionRequest: MessageFns<DeleteSessionRequest> = {
  encode(message: DeleteSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DeleteSessionRequest>, I>>(base?: I): DeleteSessionRequest {
    return DeleteSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteSessionRequest>, I>>(object: I): DeleteSessionRequest {
    const message = createBaseDeleteSessionRequest();
    message.roomId = object.roomId ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseDeleteSessionResponse(): DeleteSessionResponse {
  return { success: false };
}

export const DeleteSessionResponse: MessageFns<DeleteSessionResponse> = {
  encode(message: DeleteSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DeleteSessionResponse>, I>>(base?: I): DeleteSessionResponse {
    return DeleteSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteSessionResponse>, I>>(object: I): DeleteSessionResponse {
    const message = createBaseDeleteSessionResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseListenRequest(): ListenRequest {
  return { roomId: "", userId: "" };
}

export const ListenRequest: MessageFns<ListenRequest> = {
  encode(message: ListenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListenRequest>, I>>(base?: I): ListenRequest {
    return ListenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListenRequest>, I>>(object: I): ListenRequest {
    const message = createBaseListenRequest();
    message.roomId = object.roomId ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseSfuEvent(): SfuEvent {
  return {
    trackAddedUserId: undefined,
    trackAddedStreamId: undefined,
    trackEvent: undefined,
    renegotiateSdpOffer: undefined,
    sdpAnswer: undefined,
    iceCandidate: undefined,
    caption: undefined,
  };
}

export const SfuEvent: MessageFns<SfuEvent> = {
  encode(message: SfuEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackAddedUserId !== undefined) {
      writer.uint32(10).string(message.trackAddedUserId);
    }
    if (message.trackAddedStreamId !== undefined) {
      writer.uint32(18).string(message.trackAddedStreamId);
    }
    if (message.trackEvent !== undefined) {
      TrackAddedEvent.encode(message.trackEvent, writer.uint32(26).fork()).join();
    }
    if (message.renegotiateSdpOffer !== undefined) {
      writer.uint32(34).string(message.renegotiateSdpOffer);
    }
    if (message.sdpAnswer !== undefined) {
      writer.uint32(42).string(message.sdpAnswer);
    }
    if (message.iceCandidate !== undefined) {
      writer.uint32(50).string(message.iceCandidate);
    }
    if (message.caption !== undefined) {
      CaptionEvent.encode(message.caption, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SfuEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSfuEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trackAddedUserId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.trackAddedStreamId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.trackEvent = TrackAddedEvent.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.renegotiateSdpOffer = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sdpAnswer = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.iceCandidate = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.caption = CaptionEvent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SfuEvent>, I>>(base?: I): SfuEvent {
    return SfuEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SfuEvent>, I>>(object: I): SfuEvent {
    const message = createBaseSfuEvent();
    message.trackAddedUserId = object.trackAddedUserId ?? undefined;
    message.trackAddedStreamId = object.trackAddedStreamId ?? undefined;
    message.trackEvent = (object.trackEvent !== undefined && object.trackEvent !== null)
      ? TrackAddedEvent.fromPartial(object.trackEvent)
      : undefined;
    message.renegotiateSdpOffer = object.renegotiateSdpOffer ?? undefined;
    message.sdpAnswer = object.sdpAnswer ?? undefined;
    message.iceCandidate = object.iceCandidate ?? undefined;
    message.caption = (object.caption !== undefined && object.caption !== null)
      ? CaptionEvent.fromPartial(object.caption)
      : undefined;
    return message;
  },
};

/**
 * SfuService defines the gRPC interface for the Rust Selective Forwarding Unit (SFU).
 * It handles peer session management, signaling, and media routing in the Data Plane.
 */
export interface SfuService {
  /**
   * CreateSession initializes a new WebRTC session for a peer in the Rust SFU.
   * The SFU acts as the "passive" side (or answerer) in most cases, but here it
   * prepares resources and may return an SDP offer if configured to initiate.
   * In the current architecture:
   * 1. Backend calls CreateSession
   * 2. SFU creates PeerConnection
   * 3. SFU returns CreateSessionResponse (containing SDP Offer)
   */
  CreateSession(request: CreateSessionRequest): Promise<CreateSessionResponse>;
  /**
   * HandleSignal forwards protocol messages (SDP Answer, ICE Candidates) from the Client
   * to the SFU. This allows the SFU to complete the WebRTC handshake.
   */
  HandleSignal(request: SignalMessage): Promise<SignalResponse>;
  /**
   * DeleteSession tears down a peer's WebRTC session and releases all associated resources
   * (transceivers, tracks, ports).
   */
  DeleteSession(request: DeleteSessionRequest): Promise<DeleteSessionResponse>;
  /**
   * ListenEvents establishes a server-side stream to receive asynchronous events from the SFU.
   * Events include:
   * - New tracks published by other peers
   * - ICE candidates generated by the SFU
   * - Renegotiation requests
   */
  ListenEvents(request: ListenRequest): Observable<SfuEvent>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
