// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: proto/summary-service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "summary_service";

/** SummaryRequest contains the information needed to generate a summary. */
export interface SummaryRequest {
  /** The unique identifier of the room to summarize */
  roomId: string;
}

/** SummaryResponse contains the generated summary and action items. */
export interface SummaryResponse {
  /** The room ID this summary is for */
  roomId: string;
  /** The generated meeting summary text */
  summary: string;
  /** List of extracted action items from the meeting */
  actionItems: string[];
}

function createBaseSummaryRequest(): SummaryRequest {
  return { roomId: "" };
}

export const SummaryRequest: MessageFns<SummaryRequest> = {
  encode(message: SummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SummaryRequest>, I>>(base?: I): SummaryRequest {
    return SummaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SummaryRequest>, I>>(object: I): SummaryRequest {
    const message = createBaseSummaryRequest();
    message.roomId = object.roomId ?? "";
    return message;
  },
};

function createBaseSummaryResponse(): SummaryResponse {
  return { roomId: "", summary: "", actionItems: [] };
}

export const SummaryResponse: MessageFns<SummaryResponse> = {
  encode(message: SummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.summary !== "") {
      writer.uint32(18).string(message.summary);
    }
    for (const v of message.actionItems) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionItems.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SummaryResponse>, I>>(base?: I): SummaryResponse {
    return SummaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SummaryResponse>, I>>(object: I): SummaryResponse {
    const message = createBaseSummaryResponse();
    message.roomId = object.roomId ?? "";
    message.summary = object.summary ?? "";
    message.actionItems = object.actionItems?.map((e) => e) || [];
    return message;
  },
};

/**
 * SummaryService generates meeting summaries and action items.
 * This service is called after a meeting concludes to provide
 * participants with a summary of what was discussed.
 */
export interface SummaryService {
  /** Generates a summary for a concluded meeting room. */
  Summarize(request: SummaryRequest): Promise<SummaryResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
