# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/stream-processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/stream-processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/stream-processor.proto\x12\x10stream_processor\"M\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\"V\n\x0c\x43\x61ptionEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x12\n\nconfidence\x18\x04 \x01(\x01\x32\x64\n\x11\x43\x61ptioningService\x12O\n\x0bStreamAudio\x12\x1c.stream_processor.AudioChunk\x1a\x1e.stream_processor.CaptionEvent(\x01\x30\x01\x42\x64Zbgithub.com/RoseWrightdev/Video-Conferencing/backend/go/gen/stream_processor/proto;stream_processorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.stream_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zbgithub.com/RoseWrightdev/Video-Conferencing/backend/go/gen/stream_processor/proto;stream_processor'
  _globals['_AUDIOCHUNK']._serialized_start=50
  _globals['_AUDIOCHUNK']._serialized_end=127
  _globals['_CAPTIONEVENT']._serialized_start=129
  _globals['_CAPTIONEVENT']._serialized_end=215
  _globals['_CAPTIONINGSERVICE']._serialized_start=217
  _globals['_CAPTIONINGSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
