# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import stream_processor_pb2 as proto_dot_stream__processor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/stream_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CaptioningServiceStub(object):
    """CaptioningService provides real-time audio transcription and captioning.
    The SFU sends audio chunks via bidirectional streaming, and the service
    returns caption events as they are generated.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/stream_processor.CaptioningService/StreamAudio',
                request_serializer=proto_dot_stream__processor__pb2.AudioChunk.SerializeToString,
                response_deserializer=proto_dot_stream__processor__pb2.CaptionEvent.FromString,
                _registered_method=True)


class CaptioningServiceServicer(object):
    """CaptioningService provides real-time audio transcription and captioning.
    The SFU sends audio chunks via bidirectional streaming, and the service
    returns caption events as they are generated.
    """

    def StreamAudio(self, request_iterator, context):
        """Bidirectional streaming: SFU sends audio chunks, Service sends back captions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptioningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=proto_dot_stream__processor__pb2.AudioChunk.FromString,
                    response_serializer=proto_dot_stream__processor__pb2.CaptionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream_processor.CaptioningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream_processor.CaptioningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CaptioningService(object):
    """CaptioningService provides real-time audio transcription and captioning.
    The SFU sends audio chunks via bidirectional streaming, and the service
    returns caption events as they are generated.
    """

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/stream_processor.CaptioningService/StreamAudio',
            proto_dot_stream__processor__pb2.AudioChunk.SerializeToString,
            proto_dot_stream__processor__pb2.CaptionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
